### ISSUE TITLE
Add optional to disable maxDomainsToCheck. 

### ISSUE THREAD

**Issue by t0xodile** [PortSwigger/param-miner#101]
Hello!
I'd love to be able to disable the feature that exit's early if no interesting results are found within the first 100 attempts or so. For larger lists this would be really handy. 

The relevant section of code is below. 

```
while ((subdomain = subdomainProvider.getNext()) != null && !Utilities.unloaded.get()) {
            checked += 1;
           if (checked > maxDomainsToCheck) {
                //Utilities.out("Bailing early on "+domain);
                break;
           }
```

**Comment by albinowax** [comment]
Good idea! Could I tempt you to make a pull request? It's pretty straightforward:

Registering a config option:
https://github.com/PortSwigger/param-miner/blob/ba2e0f578a6bc59d28a66fc77991238423ac9e40/src/burp/Lenscrack.java#L17

Checking the value of the config option:
https://github.com/PortSwigger/param-miner/blob/ba2e0f578a6bc59d28a66fc77991238423ac9e40/src/burp/Lensprobe.java#L136

**Comment by t0xodile** [comment]
Absolutely! 
Raised it here -> https://github.com/PortSwigger/param-miner/pull/102
