### ISSUE TITLE
Feature request: Disable setPath(baseReq, "/")

### ISSUE THREAD

**Issue by t0xodile** [PortSwigger/param-miner#104]
This line in Lensmin.java is causing trouble in some edge-cases for me. Specifically https connections to "/" that get redirected to the Host header's location plus /homepage for example. 

`Utilities.setPath(baseReq, "/"); // does this make sense?`

If  you reckon it's a good thing to have, then I'll happily raise a pull request with a new option to disable it? Otherwise if it makes no difference, then I reckon its worth removing. 

\\Tom

**Comment by albinowax** [comment]
Can you try removing it in your build and seeing if you get any negative side effects?

**Comment by t0xodile** [comment]
Just realised that it obviously makes a huge difference for detecting new routes... since we want to see the home page (if any) not a, most likely, 404 page for the internal host... 

That said, it could still be useful to have as an option in individual cases where you know a request towards / will break the detection of internal hosts. I'll test this out now.

**Comment by t0xodile** [comment]
Okayyyy so I get basically the same results with it commented out or not. But I still feel like this is worth throwing behind an option given that generally speaking.... I wanna see the home page of the internal host and not a random guess at a path. 

I'll raise a pull when I can (probably tomorrow) and we can go from there!

**Comment by t0xodile** [comment]
Added in https://github.com/PortSwigger/param-miner/pull/105. 
Thanks!
