### ISSUE TITLE
param-miner does not pause 

### ISSUE THREAD

**Issue by fuzzerk** [PortSwigger/param-miner#13]
Is there a proper way to pause param-miner? It is my understanding that hitting the big 'Pause All' button on the main dashboard is intended to pause all automated scanning. Param-miner is not paused by this functionality and in order for me to stop it I'm forced to shut down burp or disable the param-miner plugin.

**Comment by albinowax** [comment]
You're right that there is no way to pause param miner. Unfortunately I'm unlikely to add this as a feature because it would be quite a lot of work. As a really terrible workaround, you could install distribute damage and crank the throttle up really high. I'll mention this to the Burp desktop team - they might be able to fix it for all extensions on their side.

**Comment by shchypylov** [comment]
Hi @albinowax, any update on this so far?

**Comment by albinowax** [comment]
Nope sorry realistically you'll need to code this if you want it.

**Comment by ChristianPao** [comment]
Unloading the extension will cause it to abort. I'm not talking about removing it, but just unloading it. It takes one tick.

**Comment by glaucusec** [comment]
> Unloading the extension will cause it to abort. I'm not talking about removing it, but just unloading it. It takes one tick. The message will be: Extension unloaded - aborting attack Attack aborted by exception Edit: Ok, I just saw that OP mentions "disable the param-miner plugin", I guess we're talking about the same thing.

Thanks man.

**Comment by irsdl** [comment]
@albinowax is there any way pause and cancel can now be implemented with the power of AI?

**Comment by albinowax** [comment]
If you've manually verified they work as intended, yes.

**Comment by an1msh** [comment]
Were there any updates to this
