### ISSUE TITLE
Param-miner exceeds maximum allowed number of headers in target application

### ISSUE THREAD

**Issue by mcgyver5** [PortSwigger/param-miner#16]
In my application logs, param-miner (using "guess headers") causes the following exception:

` java.lang.IllegalStateException: More than the maximum allowed number of header                                                                                                                             s, [100], were detected.`

I can't seem to find a setting that will prevent this from happening.  It would be good to have a way to do this to make the extension quieter.

**Comment by albinowax** [comment]
You can use the 'max bucketsize' option to limit the number of headers it tries at once

...I should really name my settings better
