### ISSUE TITLE
gradle build produces .jar file that Burp cannot load

### ISSUE THREAD

**Issue by mcgyver5** [PortSwigger/param-miner#19]
running `gradle build` results in a param-miner.jar that gives the following error when added to Burp:

`Failed to import the Apache Commons Lang library. You can get it from http://commons.apache.org/proper/commons-lang/`

running `gradle fatJar` results in a param-miner-all.jar that works

version = Burp Suite Community Edition v2.1.04

**Comment by albinowax** [comment]
Thanks, I've updated the docs to reflect this.
