### ISSUE TITLE
It seems like that doesn't work normally

### ISSUE THREAD

**Issue by a13202026257** [PortSwigger/param-miner#23]
I use cmd to excute burp pro V2.0.0.11( jre 1.8) ,and it output these thing ,I can't find something available,
![image](https://user-images.githubusercontent.com/37725167/76628008-02295c00-6577-11ea-950f-2c1c8ddcbdea.png)
![image](https://user-images.githubusercontent.com/37725167/76628314-7ebc3a80-6577-11ea-955f-ea139453fc4f.png)
what should I do？
thks

**Comment by fa1c0n1** [comment]
I have the same problem, too.
When I use this burp extension to scan the web cache poisoning labs in portswigger，it looks like do nothing..
![image](https://user-images.githubusercontent.com/11158624/82748683-9402e000-9dd6-11ea-8cf4-1ce9bac7ffcd.png)

and is there anything problem in my Param Miner attack config?
![image](https://user-images.githubusercontent.com/11158624/82748722-d0364080-9dd6-11ea-8d7a-6d1bb67bb5f1.png)

**Comment by realArcherL** [comment]
Try adjusting the bucket size to 999, should work then.

#2

**Comment by albinowax** [comment]
I've tweaked the bucketsize detection to factor in long response times, which resolves this issue.
