### ISSUE TITLE
headers list suggestion

### ISSUE THREAD

**Issue by HiddeSmit** [PortSwigger/param-miner#25]
Hi,

Based on this research: https://telekomsecurity.github.io/2020/05/smuggling-http-headers-through-reverse-proxies.html

I was wondering if it is useful to convert and append the headers which are currently using hyphens to underscores.

It significantly increases the headers list size, so I am curious about your opinion if this is worth the effort or not.

**Comment by albinowax** [comment]
This feature is already present - it's the "try -_ bypass" option

**Comment by HiddeSmit** [comment]
Oh wow..

I'm so sorry that I didn't see this. 
Even went through the options to check for custom wordlist but didn't see that option.

Thank you for the quick response, I appreciate it!
