### ISSUE TITLE
Implementing blacklist

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/param-miner#26]
Would it be possible to add a new menu item with user-specified blacklist? I found a unique parameter, which poisons the cache for 15 minutes and it does so every time I'm running Param Miner for discovering another unlinked inputs. With such blacklist, I could simply add it there and not DoS the platform during test:)
Like "custom blacklist path" would be amazing:)

**Comment by albinowax** [comment]
If you toggle 'max one per host' Param Miner will avoid using a parameter that it has already detected on a given host. I think this will solve your problem.
