### ISSUE TITLE
why param miner insert random string to payload

### ISSUE THREAD

**Issue by nancheal** [PortSwigger/param-miner#28]
...
xl81kpe5e5o9jpqrkbk100d63nikjllt=wrtqvaisepy1cikq; v4x3wk20ccumtpjkuyl7pohld5xs5h3v=wrtqvaxpzh7efjkq; iw32dfo7giveam3xfhvdaj6m0ndt68ug=wrtqvawmai2mnqkq; yasnbucb9tzgpsjsbqcyjv7gtu5mctzh=wrtqvarx1lwlmtkq; ysbhqcjel7dpmyqzhzxq201p3ozvyx28=wrtqvaxsrwubnkkq; s8003uthqnn0ax1jaeeqhn78ljalwg2e=wrtqvakovpsonckq; idudlblspt49gto8qtop702sa6a3y1b7=wrtqvaifku6i4pkq; tjj709gf1m49sxtmd7lvwj6az9b19uq7=wrtqvao249g7pbkq; wmufpmxikkz7q6vxvgu9ljpf0o1gsgzy=wrtqvaxlidl7cekq; tur026wwwdx7vnodndci91mpwzov86t0=wrtqvag4l47ovzkq; mz2396r3q8q6myo12k9jgh39hi4bfqps=wrtqvak5hjxpezkq; su7vuubt2l6sjxwbs3rvf2079i5z3pmk=wrtqvaszwuevsgkq; rqegjencj8es38cu8twf0hynh6koru16=wrtqvayy8f27q2kq; q77vmdwmjdsidsz98eyexlhwdt75wyd4=wrtqvapftvxkznkq; m56rqkdwgxhvxhp1i6r06vo8s6bedtbs=wrtqvaz114tyyckq; zsz8sawmvuh2f7srf5xit7km8msweybb=wrtqvaxk4zlz5bkq; l0mfj8xh36kjs1l13fzbslkp3qa6rak1=
....
param miner will add this random param to cookie and header mybe param guess too, what is the purpose to do this, is there any way to avoid this?

**Comment by nancheal** [comment]
i think param miner is to guess the max number of param the web site cat handler by this way, is that right?

**Comment by realArcherL** [comment]
This can be solved if you adjust your bucket size, I adjusted mine to 999. I am not sure exactly why it works, can't say anything without being absolutely certain. 

https://github.com/PortSwigger/param-miner/issues/2

**Comment by albinowax** [comment]
Random values are used for various purposes, one of which is cachebusting.
