### ISSUE TITLE
Custom Wordlist not Working

### ISSUE THREAD

**Issue by theleecher** [PortSwigger/param-miner#30]
I'm trying to test custom header with the custom wordlist option, but it's not working, what is the problem
![head1](https://user-images.githubusercontent.com/16206326/89704768-3a32a080-d957-11ea-82c6-86f27977e8a4.jpg)
![head2](https://user-images.githubusercontent.com/16206326/89704769-3b63cd80-d957-11ea-9102-76b17a94da60.jpg)
![head3](https://user-images.githubusercontent.com/16206326/89704770-3bfc6400-d957-11ea-8fc9-f9d900f10dd3.jpg)

**Comment by albinowax** [comment]
Are you running Burp as root?

**Comment by theleecher** [comment]
> Are you running Burp as root?
Yes i'm running it on Kali Linux

**Comment by albinowax** [comment]
On kali, the default user doesn't have root privs unless you use sudo. I think this is probably the cause of this problem.
