### ISSUE TITLE
Burp not displaying results

### ISSUE THREAD

**Issue by suaaz** [PortSwigger/param-miner#32]
Burp version -- burp suite community edition v2020.8 
Param miner -- version 1.20
![IMG_20200819_150837](https://user-images.githubusercontent.com/33347240/90645685-2bd56600-e22e-11ea-812e-0200e663f58a.jpg)
![IMG_20200819_150817](https://user-images.githubusercontent.com/33347240/90645698-2e37c000-e22e-11ea-8ad1-b667bcb3f429.jpg)
![IMG_20200819_150806](https://user-images.githubusercontent.com/33347240/90645704-3132b080-e22e-11ea-9577-9ccf31f8b8d9.jpg)

**Comment by albinowax** [comment]
Param Miner prints some output to that pane as soon as it's loaded, so it's very strange that it's blank. I guess you're either looking at the wrong extension's output pane, or hit the 'Clear' button?

**Comment by albinowax** [comment]
I've tweaked the bucketsize detection to factor in long response times, which resolves this issue.
