### ISSUE TITLE
Add dynamic cachebuster turned on results in session errors

### ISSUE THREAD

**Issue by pritchyspritch** [PortSwigger/param-miner#34]
I recently browsed a rails site that would throw a session expired error every time I tried to use a web form. 

I tracked the problem down to the dynamic cachebuster being turned on in param miner, every time I sent a request to the site with dynamic cachebuster turned on it would be caught by the following rails error:

`rescue_from ActionController::InvalidAuthenticityToken, with: :session_expired`

Would this be a bug in param miner itself or is it likely to be a bug in the site/cache?

**Comment by albinowax** [comment]
It's not really a bug in either; a small number of sites don't like unexpected parameters, which is why you can toggle that option off in param miner.
