### ISSUE TITLE
Access control Allow origin removed in preflight request

### ISSUE THREAD

**Issue by yongicobay** [PortSwigger/param-miner#35]
Hi,
After having upgraded param miner, i observed that ACAO header were removed from OPTIONS request, causing application i tested to fail login. I suspect param miner to be the cause of that problem, because it only occurs when param miner is loaded, but i don't understand why parma miner would do that, neither how i could potentially change it via a setting. Could you help me ?

And thank you for your awesome research and tools !

**Comment by albinowax** [comment]
If you enable thestatic or dynamic cache-buster options, Param Miner places a cache-buster in various places including the Origin header which could cause this behaviour. You can fix this by using the 'Reset Settings' button to get back to default settings.
