### ISSUE TITLE
Param Miner changing something in background without any way to debug

### ISSUE THREAD

**Issue by WHHackersBR** [PortSwigger/param-miner#4]
When I send a request through Burp Repeater without the Param Miner, I see a regular website; when I activate the Param Miner and replay the same request, I see a JBoss admin page.

I am very interested in how the Param Miner is making me see a JBoss page, but I cannot find what it is inserting in the request.

I am using it in the Burp beta version (probably 2.03beta).

**Comment by WHHackersBR** [comment]
Maybe I found the issue.

The extension is adding automatically `fcbz` everywhere.

**Comment by albinowax** [comment]
This is an intentional feature to prevent accidental cache poisoning. You can toggle it with the option "add fixed cache buster"

**Comment by WHHackersBR** [comment]
I believe the problem here is not the parameter per se, but why do you send it even in my requests through Burp Repeater?
