### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by mikedesu** [PortSwigger/param-miner#49]
The default wordlist points to a Linux path: /usr/share/dict/words
I've tried changing this thinking that it was a path issue but the following formats fail:

C:/my/path/file.txt
C:\my\path\file.txt
C:\\my\\path\\file.txt

I'd love to be able to use this tool, it seems really useful but I am having difficulty even getting it to run once at all

**Comment by albinowax** [comment]
This works for me with C:\path\to\file

Could you share a screenshot of your config?

**Comment by mikedesu** [comment]
The full path is to the effect of:  C:\Users\user\OneDrive\Documents\SecLists\Discovery\Web-Content\burp-parameter-names.txt
![paramminer3](https://user-images.githubusercontent.com/165251/108757476-80c0a480-750f-11eb-99af-eabcfe52f99e.png)

Attempting to launch any of the param miner attacks on a page or domain seems to fail with no visible output indicating anything is running at all. I do this by right-clicking a subdomain or page in "Target" and then clicking one of the attacks under the "Param Miner" context menu.

This has been the case in both Burp Pro and Burp Community.

**Comment by albinowax** [comment]
You need to check the 'use custom wordlist' box to use your custom wordlist

**Comment by mikedesu** [comment]
LOL ok well now I feel dumb having not seen that, but from a UI/UX-perspective, can I be faulted for eyeballing right past it? Could you move that checkbox so that it is right below or above the custom wordlist path? Thanks again albinowax, I will give this a shot now.

**Comment by albinowax** [comment]
Yeah it did used to be next to the path but clearly moved itself at some point
