### ISSUE TITLE
Ability to use custom headers as cache busters.

### ISSUE THREAD

**Issue by kinguardo** [PortSwigger/param-miner#56]
Some caches do not include any **GET** parameters nor the headers that get modified automatically by ParamMiner in their keyed input. Instead they only see some particular headers as a keyed input that aren't accounted for by the current functionality. Therefore it would be convenient to have an option to add custom headers as a cache buster.

One example could be some configurations of **CloudFlare** that disable keyed input in GET parameters or any headers except for `x-http-method-override` which is **always** considered a keyed input by the **CloudFlare** and requests containing it are guaranteed to be passed to the back-end for further processing.

**Comment by m0pam** [comment]
Bump for this one....

**Comment by albinowax** [comment]
Done!
