### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/param-miner#61]
Hi,
After I've updated to the newest version, and trying to run Param Miner on host which supports HTTP/2, the extension takes all the memory and doesn't release it at all, unless Burp is restarted. I've disabled Logger, and all other extensions so I'm quite certain the problem is in this one. I've tried both HTTP/1.1 as well as HTTP/2, but it still persists. 
![image](https://user-images.githubusercontent.com/4717664/128824620-9278d939-eef4-4697-8a62-48f3687fe333.png)
My settings are following:
![image](https://user-images.githubusercontent.com/4717664/128824670-66ce57ee-3d59-463c-aead-761ca008ae14.png)
When I start guessing Headers, I can see memory is consumed and once finished, it is still retained (I need to restart Burp). When I try to bruteforce GET parameters, the problem is much worse as I have no idea when it finishes.

**Comment by albinowax** [comment]
Thanks for the report. We've tracked this down to an issue in Burp Suite 2020.8 and the team is working on getting a release out to fix this ASAP.

**Comment by albinowax** [comment]
The fix is now out: https://portswigger.net/burp/releases/professional-community-2021-8-1
