### ISSUE TITLE
paramMiner freezes after queuing attacks

### ISSUE THREAD

**Issue by MMquant** [PortSwigger/param-miner#62]
**Description**
paramMiner freezes after issuing an attack.

**Steps to reproduce**
1. Select Guess GET parameters
![image](https://user-images.githubusercontent.com/20891620/130771877-c524890f-537c-41c3-9238-af37e7f5111d.png)
2. Set attack config as follows and click OK
![image](https://user-images.githubusercontent.com/20891620/130772071-6d9dbd93-9dca-407e-a903-f24e51a1eccb.png)
3. Inspect Logger 
![image](https://user-images.githubusercontent.com/20891620/130772274-d996c498-4bfd-4a97-be72-38972d592399.png)
4. Inspect paramMiner's log and error outputs
![image](https://user-images.githubusercontent.com/20891620/130772394-9d458ea3-efcb-4b7b-b087-05f88ee38a71.png)
![image](https://user-images.githubusercontent.com/20891620/130772436-827f9191-d45d-4914-b2e7-d99df734d1d2.png)

**Additional info**
Connection to target server runs over SOCKS proxy on localhost.
Target URL is reachable with other tools (intruder, scanner, repeater, ...)
Even that no requests are made/visible in the Logger, Burp still heavily loads the CPU
![image](https://user-images.githubusercontent.com/20891620/130779707-f5dfe3c5-81b9-442f-b34f-780b5b7eca80.png)
Under Burp 2021.6.2 paramMiner works perfectly.

**Versions**
Burp version 2021.8
paramMiner version v1.31
albinowaxUtils v0.5

**Comment by hishammir** [comment]
Same issue here

**Comment by albinowax** [comment]
@hishammir can you share full repro steps targeting a site I can access?

**Comment by albinowax** [comment]
I believe this is a separate issue - the original one was caused by Burp 2021.8. I've copied it over to here: https://github.com/PortSwigger/param-miner/issues/82

If you can provide repro steps, including a screenshot of your param miner settings, that would be really useful.
