### ISSUE TITLE
Disable the addition of the cachebuster to the Origin header

### ISSUE THREAD

**Issue by hacks2learn** [PortSwigger/param-miner#65]
Hello

Thanks for this great tool, its wonderful to use!

Today while testing a site which heavily uses CORS, I noticed that as soon as I enabled the "Add 'fcbz' cachebuster " - the application completely stopped working during to CORS checks failing.

It appeared that Param Miner was replacing the original Origin with:

Origin: https://fcbz.com

Which triggered the OPTIONS pre-flight check in the browser and then failed.

Is it possible skip the Origin header field?  Or add some type of "ignore-these-headers" ?

Thanks
Marco

**Comment by kinguardo** [comment]
I believe you are just forgetting to uncheck this option:

![2022-01-24_19-16](https://user-images.githubusercontent.com/45787099/150799358-ab676fa9-dfbe-40d8-853d-4b806c946b14.png)

**Comment by rloretan** [comment]
In case anyone else ends up here, because they don't find the _include-origin_ option: My window manager sized the settings pop up in a way where it had 3 columns and only 2 were showing. -> scroll horizontally
