### ISSUE TITLE
Param Miner injection breaks legacy apps

### ISSUE THREAD

**Issue by thedarkmint** [PortSwigger/param-miner#7]
Hello James, 

 A small observation I came across in Param-miner. I am testing a legacy app, after my initial login post request with credentials  I was getting an invalid parameter error and  was redirected to the login page.

The app worked fine without burp and the moment I went through burp, I was redirected to the login page. After lots of digging around I found out that its because of param-miner introducing **fcbz=1** at the end of the URL. I understand that's the way the plugin works to find hidden params but as its not shown in burp proxy, it was difficult to find what was causing the issue.

As the HTTP trace with and without Burp seemed similar but the app was breaking, the fact that fcbz=1 was added can be seen through Wireshark.

 May be it would be useful to indicate where the injection is happening so that its easy to trouble shoot if something breaks. Particularly when running legacy apps with hardware connected , Param-Miner was the last place I thought about for trouble shooting  :) 

Just mentioning it here as it might be useful for someone having similar issues.

**Comment by ldionmarcil** [comment]
I'm also facing this. It was my understanding that the cache buster parameter was applied from Param Miner requests, but it appears that it's applied to proxy and repeater requests as well. Is this intended behavior? It triggers a lot of 302s for me.

**Comment by albinowax** [comment]
I've addressed this by letting people toggle off the fcbz cache-buster using the settings.
