### ISSUE TITLE
Implement delays

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/param-miner#72]
I've come across an environment, which is very picky about the amount of requests sent per a time window. If the limit is reached, I simply get 429: Too Many Requests. I don't see Param Miner slowing down, nor do I see any setting which would help me (e.g. implementing a delay or a single thread). Could you please add this function? Or even better automatically observe if such scenario is reached, and try to "cool it down" when firing new request.
Thanks:)

**Comment by albinowax** [comment]
You can delay/throttle any extension using the separate Distribute Damage extension.
