### ISSUE TITLE
Param mining is not happening in Burp Suite Pro v2022.9-15774

### ISSUE THREAD

**Issue by samincube** [PortSwigger/param-miner#76]
I am observing the weird behavior of Param Miner on the recent Early Adopter version of Burp Pro (v2022.9-15774) - as soon as I start the brute force, I can observe 20 requests in the logger that are being sent by Param miner with cache buster only and without the actual param values to be brute-forced. After these 20 requests, the queue is finished. No errors in the Extensions log panel. 
To be sure, I reinstalled it and performed settings reset to default ones. Still observing the same.

This happens for GET and urlencoded/multipart POST parameter brute force. However, header and JSON parameter brute force works fine.

Tool versions:
albinowaxUtils v1.03
Param Miner v1.4d

Checked for v2022.9-15774 on Windows system and on Mac - same situation on both.

Seems to be worth checking since it renders Param miner partially unusable, just not sure if it's an extension itself or something with the new Burp version.

**Comment by albinowax** [comment]
Thanks, I'll take a look

**Comment by albinowax** [comment]
We've confirmed that this was introduced in the latest Burp Suite early adopter release. It will be fixed in the next early adopter update. Thanks again for the report.

**Comment by albinowax** [comment]
This release should fix the issue: https://portswigger.net/burp/releases/professional-community-2022-9-1

**Comment by samincube** [comment]
Can confirm, on the early adopter version v2022.9.1-16047 Param miner now works correctly and as expected. Nice job!
