### ISSUE TITLE
Paraminer adding cachebuster to repeater request

### ISSUE THREAD

**Issue by wlayzz** [PortSwigger/param-miner#79]
Hi team ! 

I notice a strange behavior with paraminer. If a run a scan with cache buster enabled. Then after the scan is finish when I repeat a request on repeater the cachebuster is added to the request without been noticed in repeater.

![image](https://user-images.githubusercontent.com/34021743/199619154-455b671e-4d26-4a9f-a015-12cf6ea8271c.png)

The request in logger has the cachebuster parameter : 
![image](https://user-images.githubusercontent.com/34021743/199619216-cf356c5b-fdda-4a5a-95ea-e12881df8aa5.png)

I don't know if this behavior is normal but it tooks my some times to figure out.

I find this can be disabled on Menu->Paraminer->Settings and uncheck add cachebuster.

Btw thx for the good job, I really appreciate Burp

**Comment by albinowax** [comment]
Yes, this is the fcbz cache-buster. That option is disabled by default so I imagine you turned it on when launching your scan... unfortunately that's intentional. Thanks for the report anyways.
