### ISSUE TITLE
Standalone version?

### ISSUE THREAD

**Issue by savagejen** [PortSwigger/param-miner#8]
Is there a standalone version of this, or some way to run it without checking for all the other things burp scans for?

**Comment by albinowax** [comment]
If you select one or more HTTP requests and right click, you should see a 'Guess [params/headers/etc]' option. This will launch param miner only, and not trigger any burp scan checks.

If you want a command line alternative, I'd suggest https://github.com/s0md3v/Arjun

Sorry for the slow response time!
