### ISSUE TITLE
Guess multipart parameters not working: java.lang.UnsupportedOperationException: Action is not supported for this parameter type

### ISSUE THREAD

**Issue by mk7120** [PortSwigger/param-miner#87]
When using param-miner to guess multipart parameters (POST). I observed that it did not work correctly, the extension only sent one request (GET) and stopped with the error "java.lang.UnsupportedOperationException: Action is not supported for this parameter type". 

Tool versions:
albinowaxUtils v1.03
Param Miner v1.4f
Burp v2023.10-22956 (Early Adopter)

**Comment by albinowax** [comment]
Unfortunately this is due to a Burp API limitation. As a workaround you might be able to use the 'change request encoding' option before sending the request to param miner.

**Comment by mk7120** [comment]
Thank you for your suggestion, but this workaround is not fixed for my case. I faced the page for uploading files, by changing from "multipart" to "x-www-form-urlencoded" the server stopped at the error screen immediately without continuing its logic

**Comment by albinowax** [comment]
That's the only workaround, so you're out of luck - I'd suggest mining manually with Turbo Intruder instead.
