### ISSUE TITLE
Username Albinowax is hardcoded in user-agent

### ISSUE THREAD

**Issue by YouGina** [PortSwigger/param-miner#95]
Is that on purpose? I kind of assume that this is left by mistake, It would actually be nice if this is a configurable string.

See:
https://github.com/PortSwigger/param-miner/blob/2e41c137394a3ea4c70e3f416c3e6ae4d1579d71/src/burp/Lenscrack.java#L63

**Comment by albinowax** [comment]
Woops yep I'll fix that, thanks for reporting

**Comment by albinowax** [comment]
Fixed on master
